version: 0.0
os: linux
files:
  - source: start.sh
    destination: /home/ec2-user
  - source: before_install.sh
    destination: /home/ec2-user  
  - source: docker-compose.yml
    destination: /home/ec2-user


permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user

