version: '3'
services:
  # frontend:
  #   image: imriteek/frontend:latest
  #   #build: ./frontend/
  #   command: serve -s dist
  #   ports:
  #     - "3000:3000"

  backend:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    command: npm run server
    ports:
      - "4000:4000"

  # admin:
  #   image: imriteek/admin:latest
  #   #build: ./admin/
  #   command: serve -s dist
  #   ports: 
  #     - "3001:3000"

