version: '3'
services:
  # frontend:
  #   image: imriteek/frontend:latest
  #   #build: ./frontend/
  #   command: serve -s dist
  #   ports:
  #     - "3000:3000"

  backend:
    image: 905418426404.dkr.ecr.ap-south-1.amazonaws.com/imriteek:backend
    command: npm run server
    ports:
      - "4000:4000"

  # admin:
  #   image: imriteek/admin:latest
  #   #build: ./admin/
  #   command: serve -s dist
  #   ports: 
  #     - "3001:3000"

